# Generated by Django 5.2.8 on 2025-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
