# Generated by Django 5.2.8 on 2025-12-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_to_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
