# Generated by Django 6.0 on 2025-12-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin',
            field=models.CharField(choices=[('autoFetch', 'Auto fetch'), ('manualFetch', 'Manual fetch')], default='autoFetch', max_length=20),
        ),
    ]
