# Generated by Django 6.0 on 2025-12-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('confidence', models.FloatField(help_text='0–1 confidence score')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.article')),
            ],
            options={
                'indexes': [models.Index(fields=['country_code'], name='main_articl_country_d98657_idx'), models.Index(fields=['latitude', 'longitude'], name='main_articl_latitud_c85271_idx')],
            },
        ),
    ]
