# Generated by Django 6.0 on 2026-01-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_articlelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFetchPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
            ],
        ),
    ]
