# Generated by Django 6.0 on 2026-01-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_globalfetchpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalfetchpreferences',
            name='singleton',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
