# Generated by Django 6.0 on 2026-01-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_globalfetchpreferences_singleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalfetchpreferences',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='globalfetchpreferences',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='globalfetchpreferences',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
